services:
  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    container_name: ecommerce-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  api:
    build: .
    container_name: ecommerce-api

    environment:
      API_SECURITY_TOKEN_SECRET: ${API_SECURITY_TOKEN_SECRET}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  mysql_data: